CREATE TABLE [dbo].[PayrollFile] (
  [PayrollFileID] [int] IDENTITY,
  [PayrollFileXML] [xml] NULL,
  [LoadNumber] [int] NULL,
  [PayrollCount] [int] NULL,
  [WorkState] [varchar](50) NULL,
  [StartDate] [datetime] NULL,
  [EndDate] [datetime] NULL,
  [InvoiceRef#] [varchar](50) NULL,
  [InvoiceNumber] [varchar](50) NULL,
  [Batch] [varchar](50) NULL,
  [ProjectTitle] [varchar](100) NULL,
  [ProjectCode] [varchar](100) NULL,
  [RunDateTime] [varchar](100) NULL,
  [CompanyID] [int] NULL,
  [ProdID] [int] NULL,
  [PrintedFlag] [bit] NULL,
  [InvoicedFlag] [bit] NULL,
  [PostedFlag] [bit] NULL,
  [Status] [varchar](50) NULL,
  [TransactionDate] [datetime] NULL,
  [InvoicedDate] [datetime] NULL,
  [TotalPayrollAmount] [decimal](18, 2) NULL,
  [AutoPostInvoice] [bit] NULL,
  [AutoPostInvoiceDate] [datetime] NULL,
  [PrintStatus] [varchar](50) NULL,
  [CreatedDate] [datetime] NULL,
  [ModifiedDate] [datetime] NULL,
  [Createdby] [int] NULL,
  [Modifiedby] [int] NULL,
  [BatchNumber] [varchar](100) NOT NULL,
  [PeriodStatus] [varchar](50) NOT NULL,
  [VendorID] [int] NULL
)
GO