CREATE TABLE [dbo].[PayrollExpense] (
  [PayrollExpenseID] [int] IDENTITY,
  [Freefield1] [varchar](50) NULL,
  [Freefield2] [varchar](50) NULL,
  [FreeField3] [varchar](50) NULL,
  [PaymentAmount] [varchar](50) NULL,
  [PaymentAccount] [varchar](50) NULL,
  [PayDescription] [varchar](100) NULL,
  [EpisodeCode] [varchar](50) NULL,
  [SetCode] [varchar](50) NULL,
  [LocationCode] [varchar](50) NULL,
  [TaxCode] [varchar](50) NULL,
  [ZZ] [varchar](50) NULL,
  [ExpenseOrd] [varchar](50) NULL,
  [LineOrder] [varchar](50) NULL,
  [CreatedDate] [datetime] NULL,
  [ModifiedDate] [datetime] NULL,
  [Createdby] [int] NULL,
  [Modifiedby] [int] NULL,
  [PayrollUserID] [int] NULL,
  [PayrollFileID] [int] NULL,
  [TransactionString] [varchar](3000) NULL,
  [SegmentString] [varchar](5000) NULL,
  [COAID] [varchar](50) NULL,
  [Insurance] [varchar](100) NULL,
  [ExpenseType] [nvarchar](1) NOT NULL DEFAULT (''),
  CONSTRAINT [CK_ExpenseType] CHECK ([ExpenseType]<>'')
)
GO