//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAdjustment
    {
        public int AdjustmentID { get; set; }
        public int BankID { get; set; }
        public int ProdID { get; set; }
        public int ReconcilationID { get; set; }
        public int AdjustmentNumber { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public int UserID { get; set; }
        public string Status { get; set; }
    
        public virtual BankInfo BankInfo { get; set; }
        public virtual BankReconcilation BankReconcilation { get; set; }
    }
}
