//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankInfo
    {
        public BankInfo()
        {
            this.BankAdjustments = new HashSet<BankAdjustment>();
            this.BankReconcilations = new HashSet<BankReconcilation>();
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int BankId { get; set; }
        public string Bankname { get; set; }
        public int CompanyId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string city { get; set; }
        public string State { get; set; }
        public string zip { get; set; }
        public string Country { get; set; }
        public string RoutingNumber { get; set; }
        public string AccountNumber { get; set; }
        public string BranchNumber { get; set; }
        public string Branch { get; set; }
        public Nullable<int> Clearing { get; set; }
        public Nullable<int> Cash { get; set; }
        public Nullable<int> Suspense { get; set; }
        public Nullable<int> Bankfees { get; set; }
        public Nullable<int> Deposits { get; set; }
        public Nullable<int> SourceCodeID { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> PostiivePay { get; set; }
        public int Prodid { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string configJSON { get; set; }
    
        public virtual ICollection<BankAdjustment> BankAdjustments { get; set; }
        public virtual ICollection<BankReconcilation> BankReconcilations { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
