//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchNumber
    {
        public int BatchId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProdId { get; set; }
        public string BatchNumber1 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> InactiveDate { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
