//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public int BudgetId { get; set; }
        public int Prodid { get; set; }
        public string BudgetName { get; set; }
        public System.DateTime Createddate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public int createdby { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public string Description { get; set; }
    }
}
