//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetCategoryFinal
    {
        public int BudgetCategoryID { get; set; }
        public Nullable<int> cid { get; set; }
        public string CategoryNumber { get; set; }
        public string CategoryDescription { get; set; }
        public string CategoryFringe { get; set; }
        public string CategoryOriginal { get; set; }
        public string CategoryTotal { get; set; }
        public string CategoryVariance { get; set; }
        public Nullable<int> Budgetfileid { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<int> BudgetID { get; set; }
        public string S1 { get; set; }
        public string S2 { get; set; }
        public string S3 { get; set; }
        public string S4 { get; set; }
        public string S5 { get; set; }
        public string S6 { get; set; }
        public string S7 { get; set; }
        public string S8 { get; set; }
        public Nullable<int> COAID { get; set; }
        public string COACODE { get; set; }
    }
}
