//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetFile
    {
        public int BudgetFileID { get; set; }
        public System.DateTime Uploadeddate { get; set; }
        public int uploadedby { get; set; }
        public string Action { get; set; }
        public string Status { get; set; }
        public string Amounts { get; set; }
        public int LeaveexistingCOA { get; set; }
        public string CompanCode { get; set; }
        public int CompanyID { get; set; }
        public int prodid { get; set; }
        public int Budgetid { get; set; }
        public string UploadedXML { get; set; }
        public string S1 { get; set; }
        public string S2 { get; set; }
        public string S3 { get; set; }
        public string S4 { get; set; }
        public string S5 { get; set; }
        public string S6 { get; set; }
        public string LedgerLebel { get; set; }
        public string SegmentName { get; set; }
        public string SegStr1 { get; set; }
        public string SegStr2 { get; set; }
    }
}
