//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetDetail
    {
        public int BudgetDetailID { get; set; }
        public string AccountID { get; set; }
        public string AggPercent { get; set; }
        public string DLocation { get; set; }
        public string DetailSet { get; set; }
        public string Description { get; set; }
        public string Amount { get; set; }
        public string Unit { get; set; }
        public string X { get; set; }
        public string Unit2 { get; set; }
        public string Currency { get; set; }
        public string Rate { get; set; }
        public string Unit3 { get; set; }
        public string Unit4 { get; set; }
        public string SubTotal { get; set; }
        public string HiddenDfourthMlt { get; set; }
        public Nullable<int> BudgetFileID { get; set; }
        public Nullable<int> BudgetID { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> DetailNumber { get; set; }
    }
}
