//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAUser
    {
        public int CAUserId { get; set; }
        public int UserID { get; set; }
        public int ProdID { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public bool Status { get; set; }
        public System.DateTime Createddate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public int createdby { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public bool GroupBatchAccess { get; set; }
        public bool CanClose { get; set; }
        public Nullable<bool> AllBatchAccess { get; set; }
    }
}
