//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckSetting
    {
        public int CheckSettingID { get; set; }
        public int CompanyID { get; set; }
        public string Style { get; set; }
        public string Prefix { get; set; }
        public string Length { get; set; }
        public string StartNumber { get; set; }
        public string EndNumber { get; set; }
        public string Collated { get; set; }
        public bool PrintZero { get; set; }
        public int Copies { get; set; }
        public decimal TopMargin { get; set; }
        public decimal BottomMargin { get; set; }
        public decimal LeftMargin { get; set; }
        public decimal RightMargin { get; set; }
        public string Status { get; set; }
        public int BankID { get; set; }
        public string SectionOne { get; set; }
        public string SectionTwo { get; set; }
        public string SectionThree { get; set; }
        public int Prodid { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
