//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClosePeriod
    {
        public ClosePeriod()
        {
            this.JournalEntries = new HashSet<JournalEntry>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int ClosePeriodId { get; set; }
        public int CompanyId { get; set; }
        public int CompanyPeriod { get; set; }
        public Nullable<System.DateTime> StartPeriod { get; set; }
        public Nullable<System.DateTime> EndPeriod { get; set; }
        public string Status { get; set; }
        public string PeriodStatus { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ICollection<JournalEntry> JournalEntries { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
