//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class COA
    {
        public COA()
        {
            this.JournalEntryDetails = new HashSet<JournalEntryDetail>();
            this.Custodians = new HashSet<Custodian>();
            this.Recipients = new HashSet<Recipient>();
            this.PurchaseOrderLines = new HashSet<PurchaseOrderLine>();
            this.PCEnvelopeLines = new HashSet<PCEnvelopeLine>();
            this.InvoiceLines = new HashSet<InvoiceLine>();
        }
    
        public int COAID { get; set; }
        public string COACode { get; set; }
        public string ParentCode { get; set; }
        public string Description { get; set; }
        public string SS1 { get; set; }
        public string SS2 { get; set; }
        public string SS3 { get; set; }
        public string SS4 { get; set; }
        public string SS5 { get; set; }
        public string SS6 { get; set; }
        public string SS7 { get; set; }
        public string SS8 { get; set; }
        public Nullable<int> ProdId { get; set; }
        public Nullable<int> DetailLevel { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> AccountTypeid { get; set; }
    
        public virtual ICollection<JournalEntryDetail> JournalEntryDetails { get; set; }
        public virtual ICollection<Custodian> Custodians { get; set; }
        public virtual ICollection<Recipient> Recipients { get; set; }
        public virtual ICollection<PurchaseOrderLine> PurchaseOrderLines { get; set; }
        public virtual ICollection<PCEnvelopeLine> PCEnvelopeLines { get; set; }
        public virtual TblAccount TblAccount { get; set; }
        public virtual ICollection<InvoiceLine> InvoiceLines { get; set; }
    }
}
