//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanySetting
    {
        public int SettingID { get; set; }
        public int CompanyID { get; set; }
        public string AccountingCurrency { get; set; }
        public string ReportLabel { get; set; }
        public bool RealTimeCurrency { get; set; }
        public int FringeAccountID { get; set; }
        public int LaborAccountID { get; set; }
        public int SuspenseAccountID { get; set; }
        public System.DateTime Createddate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public int createdby { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public int ProdID { get; set; }
    }
}
