//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyGroup
    {
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        public int Prodid { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool AllCompanyFlag { get; set; }
        public bool AllowPeriodClose { get; set; }
        public bool GroupBatchAccess { get; set; }
    }
}
