//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.JournalEntries = new HashSet<JournalEntry>();
            this.JournalEntryDetails = new HashSet<JournalEntryDetail>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.PCEnvelopes = new HashSet<PCEnvelope>();
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int CompanyID { get; set; }
        public string CompanyCode { get; set; }
        public string ProductionTitle { get; set; }
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string CompanyPhone { get; set; }
        public string Contact { get; set; }
        public int Entry { get; set; }
        public int Cost { get; set; }
        public string Format { get; set; }
        public string Status { get; set; }
        public System.DateTime Createddate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public int createdby { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public int ProdID { get; set; }
        public bool Defaultflag { get; set; }
        public Nullable<System.DateTime> FiscalStartDate { get; set; }
        public string DefaultValue { get; set; }
        public Nullable<System.DateTime> PeriodStart { get; set; }
        public string Country { get; set; }
        public string PeriodStartType { get; set; }
    
        public virtual ICollection<JournalEntry> JournalEntries { get; set; }
        public virtual ICollection<JournalEntryDetail> JournalEntryDetails { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<PCEnvelope> PCEnvelopes { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
