//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRW
    {
        public int CRWID { get; set; }
        public string BudgetAccountID { get; set; }
        public string ETC { get; set; }
        public string EFC { get; set; }
        public Nullable<int> BudgetCategoryID { get; set; }
    }
}
