//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRWDetail
    {
        public int BudgetCategoryID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string AccountTotal { get; set; }
        public string CategoryNumber { get; set; }
        public string AccountNumber { get; set; }
        public string AccountDesc { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> PO { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string CategoryDescription { get; set; }
        public Nullable<int> BudgetID { get; set; }
        public Nullable<int> Budgetfileid { get; set; }
        public int COAID { get; set; }
        public Nullable<int> DetailLevel { get; set; }
    }
}
