//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRWEstimatedCost_Fix
    {
        public int ID { get; set; }
        public Nullable<int> DetailLevel { get; set; }
        public int BudgetId { get; set; }
        public int BudgetFileID { get; set; }
        public Nullable<decimal> ETC { get; set; }
        public Nullable<decimal> EFC { get; set; }
        public int COAID { get; set; }
        public Nullable<int> RefID { get; set; }
        public Nullable<int> ExpandValue { get; set; }
        public string Budget { get; set; }
        public string BlankETC { get; set; }
        public string BlankEFC { get; set; }
    }
}
