//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custodian
    {
        public Custodian()
        {
            this.PCEnvelopes = new HashSet<PCEnvelope>();
        }
    
        public int CustodianID { get; set; }
        public string CustodianCode { get; set; }
        public string Currency { get; set; }
        public int VendorID { get; set; }
        public int COAID { get; set; }
        public string COACode { get; set; }
        public Nullable<int> Setid { get; set; }
        public Nullable<int> SeriesID { get; set; }
        public int Prodid { get; set; }
        public int CompanyID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
        public int Createdy { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public bool Status { get; set; }
    
        public virtual COA COA { get; set; }
        public virtual ICollection<PCEnvelope> PCEnvelopes { get; set; }
    }
}
