//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstimatedCostSet
    {
        public int ID { get; set; }
        public Nullable<int> BudgetID { get; set; }
        public Nullable<int> BudgetFileID { get; set; }
        public Nullable<int> DetailLevel { get; set; }
        public Nullable<int> COAID { get; set; }
        public Nullable<int> SetID { get; set; }
        public string EFC { get; set; }
        public string ETC { get; set; }
        public string Budget { get; set; }
    }
}
