//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalEntryDetail
    {
        public int JournalEntryDetailId { get; set; }
        public int JournalEntryId { get; set; }
        public string TransactionLineNumber { get; set; }
        public int COAId { get; set; }
        public decimal DebitAmount { get; set; }
        public decimal CreditAmount { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string VendorName { get; set; }
        public bool ThirdParty { get; set; }
        public string Note { get; set; }
        public int CompanyId { get; set; }
        public int ProdId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string COAString { get; set; }
        public string TransactionCodeString { get; set; }
        public Nullable<int> SetId { get; set; }
        public Nullable<int> SeriesId { get; set; }
        public string TaxCode { get; set; }
        public Nullable<int> DocumentLineID { get; set; }
    
        public virtual COA COA { get; set; }
        public virtual Company Company { get; set; }
        public virtual JournalEntry JournalEntry { get; set; }
        public virtual tblVendor tblVendor { get; set; }
    }
}
