//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalEntry
    {
        public JournalEntry()
        {
            this.JournalEntryDetails = new HashSet<JournalEntryDetail>();
            this.ReconcilationAddons = new HashSet<ReconcilationAddon>();
        }
    
        public int JournalEntryId { get; set; }
        public string TransactionNumber { get; set; }
        public string Source { get; set; }
        public string Description { get; set; }
        public System.DateTime EntryDate { get; set; }
        public decimal DebitTotal { get; set; }
        public decimal CreditTotal { get; set; }
        public Nullable<int> TotalLines { get; set; }
        public Nullable<decimal> ImbalanceAmount { get; set; }
        public string AuditStatus { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public string ReferenceNumber { get; set; }
        public string BatchNumber { get; set; }
        public int ProdId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public int createdBy { get; set; }
        public Nullable<int> modifiedBy { get; set; }
        public int ClosePeriod { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string SourceTable { get; set; }
        public string DocumentNo { get; set; }
        public string CurrentStatus { get; set; }
        public Nullable<int> InvoiceIDPayment { get; set; }
        public string DocumentJSON { get; set; }
        public string DocumentJSONEdit { get; set; }
    
        public virtual ClosePeriod ClosePeriod1 { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<JournalEntryDetail> JournalEntryDetails { get; set; }
        public virtual ICollection<ReconcilationAddon> ReconcilationAddons { get; set; }
    }
}
