//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LedgerAccount
    {
        public int LedgerId { get; set; }
        public Nullable<int> SegmentId { get; set; }
        public string AccountCode { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> AccountTypeId { get; set; }
        public Nullable<bool> BalanceSheet { get; set; }
        public bool Status { get; set; }
        public Nullable<bool> Posting { get; set; }
        public Nullable<int> SubLevel { get; set; }
        public string SegmentType { get; set; }
        public Nullable<int> ParentId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public int ProdId { get; set; }
    }
}
