//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public int ModuleId { get; set; }
        public string ModuleName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int ModuleLevel { get; set; }
        public Nullable<int> Children { get; set; }
        public string Module_URL { get; set; }
    }
}
