//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyConfig
    {
        public int ConfigID { get; set; }
        public int Userid { get; set; }
        public Nullable<int> Moduleid { get; set; }
        public string ConfigType { get; set; }
        public string EntityName { get; set; }
        public Nullable<int> EntityID { get; set; }
        public Nullable<int> Trackid { get; set; }
        public Nullable<int> Codeid { get; set; }
        public Nullable<int> Valueid { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public int Prodid { get; set; }
    }
}
