//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mydefault
    {
        public int MyDefaultId { get; set; }
        public string Type { get; set; }
        public string UserType { get; set; }
        public Nullable<int> RefId { get; set; }
        public string Defvalue { get; set; }
        public int UserId { get; set; }
        public int ProdId { get; set; }
    }
}
