//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentLine
    {
        public int PaymentLineId { get; set; }
        public int PaymentId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ProdId { get; set; }
        public int BankID { get; set; }
        public string CheckNumber { get; set; }
        public bool isdeleted { get; set; }
    }
}
