//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollUser
    {
        public int PayrollUserID { get; set; }
        public Nullable<int> Expensecount { get; set; }
        public string UnionName { get; set; }
        public string UnionCode { get; set; }
        public string JobTitle { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SSN { get; set; }
        public Nullable<decimal> TotalPaymentAmount { get; set; }
        public string CheckNumber { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<int> PayrollFileID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<int> Modifiedby { get; set; }
    
        public virtual PayrollFile PayrollFile { get; set; }
    }
}
