//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollFreeField
    {
        public int PayrollFreeFieldID { get; set; }
        public Nullable<int> FreeField1 { get; set; }
        public Nullable<int> FreeField2 { get; set; }
        public Nullable<int> FreeField3 { get; set; }
        public System.DateTime createddate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public int createdby { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public int ProdID { get; set; }
        public Nullable<int> CompanyId { get; set; }
    }
}
