//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollFile
    {
        public PayrollFile()
        {
            this.PayrollExpensePosts = new HashSet<PayrollExpensePost>();
            this.PayrollExpenses = new HashSet<PayrollExpense>();
            this.PayrollUsers = new HashSet<PayrollUser>();
        }
    
        public int PayrollFileID { get; set; }
        public string PayrollFileXML { get; set; }
        public Nullable<int> LoadNumber { get; set; }
        public Nullable<int> PayrollCount { get; set; }
        public string WorkState { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string InvoiceRef_ { get; set; }
        public string InvoiceNumber { get; set; }
        public string Batch { get; set; }
        public string ProjectTitle { get; set; }
        public string ProjectCode { get; set; }
        public string RunDateTime { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> ProdID { get; set; }
        public Nullable<bool> PrintedFlag { get; set; }
        public Nullable<bool> InvoicedFlag { get; set; }
        public Nullable<bool> PostedFlag { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.DateTime> InvoicedDate { get; set; }
        public Nullable<decimal> TotalPayrollAmount { get; set; }
        public Nullable<bool> AutoPostInvoice { get; set; }
        public Nullable<System.DateTime> AutoPostInvoiceDate { get; set; }
        public string PrintStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public string BatchNumber { get; set; }
        public string PeriodStatus { get; set; }
        public Nullable<int> VendorID { get; set; }
    
        public virtual ICollection<PayrollExpensePost> PayrollExpensePosts { get; set; }
        public virtual ICollection<PayrollExpense> PayrollExpenses { get; set; }
        public virtual ICollection<PayrollUser> PayrollUsers { get; set; }
    }
}
