//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollExpense
    {
        public int PayrollExpenseID { get; set; }
        public string Freefield1 { get; set; }
        public string Freefield2 { get; set; }
        public string FreeField3 { get; set; }
        public string PaymentAmount { get; set; }
        public string PaymentAccount { get; set; }
        public string PayDescription { get; set; }
        public string EpisodeCode { get; set; }
        public string SetCode { get; set; }
        public string LocationCode { get; set; }
        public string TaxCode { get; set; }
        public string ZZ { get; set; }
        public string ExpenseOrd { get; set; }
        public string LineOrder { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<int> PayrollUserID { get; set; }
        public Nullable<int> PayrollFileID { get; set; }
        public string TransactionString { get; set; }
        public string SegmentString { get; set; }
        public string COAID { get; set; }
        public string Insurance { get; set; }
        public string ExpenseType { get; set; }
    
        public virtual PayrollFile PayrollFile { get; set; }
    }
}
