//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollCheck
    {
        public int CheckID { get; set; }
        public string PdfCheckNum { get; set; }
        public Nullable<int> PayrollUserID { get; set; }
        public string CheckPDF { get; set; }
        public Nullable<int> PayrollFileID { get; set; }
    }
}
