//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCEnvelope
    {
        public PCEnvelope()
        {
            this.PCEnvelopeLines = new HashSet<PCEnvelopeLine>();
        }
    
        public int PcEnvelopeID { get; set; }
        public int Companyid { get; set; }
        public string BatchNumber { get; set; }
        public int CustodianId { get; set; }
        public int RecipientId { get; set; }
        public string EnvelopeNumber { get; set; }
        public string Description { get; set; }
        public decimal AdvanceAmount { get; set; }
        public decimal EnvelopeAmount { get; set; }
        public decimal LineItemAmount { get; set; }
        public decimal Difference { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public int Prodid { get; set; }
        public Nullable<int> PostedBy { get; set; }
        public int ClosePeriodId { get; set; }
        public string MirrorStatus { get; set; }
        public string DocumentJSON { get; set; }
        public string DocumentJSONEdit { get; set; }
    
        public virtual Custodian Custodian { get; set; }
        public virtual Recipient Recipient { get; set; }
        public virtual ICollection<PCEnvelopeLine> PCEnvelopeLines { get; set; }
        public virtual Company Company { get; set; }
    }
}
