//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCEnvelopeLine
    {
        public int EnvelopeLineID { get; set; }
        public int PCEnvelopeID { get; set; }
        public int TransactionLineNumber { get; set; }
        public int COAID { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string LineDescription { get; set; }
        public string TransactionCodeString { get; set; }
        public Nullable<int> Setid { get; set; }
        public Nullable<int> SeriesID { get; set; }
        public int Prodid { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string CoaString { get; set; }
        public string TaxCode { get; set; }
        public string Displayflag { get; set; }
    
        public virtual tblVendor tblVendor { get; set; }
        public virtual COA COA { get; set; }
        public virtual PCEnvelope PCEnvelope { get; set; }
    }
}
