//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public int POID { get; set; }
        public string PONumber { get; set; }
        public int CompanyID { get; set; }
        public int VendorID { get; set; }
        public string VendorName { get; set; }
        public bool ThirdParty { get; set; }
        public string WorkRegion { get; set; }
        public string Description { get; set; }
        public string CurrentBalance { get; set; }
        public string BatchNumber { get; set; }
        public bool ClosePOuponPayment { get; set; }
        public string Payby { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public int ProdID { get; set; }
        public System.DateTime PODate { get; set; }
        public string COCode { get; set; }
        public int ClosePeriodId { get; set; }
        public Nullable<bool> RequiredTaxCode { get; set; }
        public decimal OriginalAmount { get; set; }
        public decimal AdjustmentTotal { get; set; }
        public decimal RelievedTotal { get; set; }
        public decimal BalanceAmount { get; set; }
        public string DocumentJSON { get; set; }
        public string DocumentJSONEdit { get; set; }
    
        public virtual ClosePeriod ClosePeriod { get; set; }
        public virtual Company Company { get; set; }
        public virtual tblVendor tblVendor { get; set; }
    }
}
