//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipient
    {
        public Recipient()
        {
            this.PCEnvelopes = new HashSet<PCEnvelope>();
        }
    
        public int RecipientID { get; set; }
        public int VendorID { get; set; }
        public int COAID { get; set; }
        public int Prodid { get; set; }
        public System.DateTime Createddate { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
        public int Createdby { get; set; }
        public string CoaString { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> SetId { get; set; }
        public Nullable<int> SeriesId { get; set; }
        public bool Status { get; set; }
    
        public virtual COA COA { get; set; }
        public virtual ICollection<PCEnvelope> PCEnvelopes { get; set; }
    }
}
