//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReconcilationAddon
    {
        public int ID { get; set; }
        public int ReconcilationID { get; set; }
        public System.DateTime SaveDate { get; set; }
        public string Status { get; set; }
        public int UserID { get; set; }
        public int JEID { get; set; }
    
        public virtual JournalEntry JournalEntry { get; set; }
        public virtual BankReconcilation BankReconcilation { get; set; }
    }
}
