//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceCode
    {
        public int SourceCodeID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public bool AP { get; set; }
        public bool JE { get; set; }
        public bool PO { get; set; }
        public bool PC { get; set; }
        public bool AR { get; set; }
        public bool PR { get; set; }
        public Nullable<bool> WT { get; set; }
        public string Thirdparty { get; set; }
        public System.DateTime Createddate { get; set; }
        public Nullable<System.DateTime> ModidiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public int CreatedBy { get; set; }
        public int ProdID { get; set; }
    }
}
