//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProduction
    {
        public int UserproductionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Prodid { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<bool> Groupbatchaccess { get; set; }
        public Nullable<bool> Canclose { get; set; }
        public Nullable<bool> Allbatchaccess { get; set; }
    
        public virtual CAUserAdmin CAUserAdmin { get; set; }
    }
}
