//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variance
    {
        public int ID { get; set; }
        public Nullable<int> BudgetID { get; set; }
        public Nullable<int> BudgetFileID { get; set; }
        public Nullable<int> COAID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<int> ProdID { get; set; }
        public Nullable<decimal> EFCOLD { get; set; }
        public Nullable<decimal> EFCNEW { get; set; }
        public string Period { get; set; }
    }
}
