//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPayrollPostAmount
    {
        public Nullable<int> PayrollFileID { get; set; }
        public string PaymentAmount { get; set; }
        public string AccountNumber { get; set; }
        public int AccountID { get; set; }
        public int ProdID { get; set; }
    }
}
